name: fpo_assist
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.3
  http: ^1.2.1
  pinput: ^4.0.0
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.1
  sizer: ^2.0.15
#  carousel_slider: ^4.2.1
  carousel_slider:
    git:
      url: https://github.com/sampaio96/flutter_carousel_slider.git
      ref: master
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  video_player: ^2.9.1
  chewie: ^1.8.1
  audioplayers: ^6.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/gif/


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Bitter
      fonts:
        - asset: fonts/Bitter-Regular.ttf

    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
